<a href="https://colab.research.google.com/github/mjnhcanhh/TH_DeepLearning/blob/main/Lab_1_Numpy_Panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

!pip install numpy

import numpy as np

# 3.1. Tạo array 1-chiều
my_list = [1, 9, 15, 39]
my_numpy_array = np.array(my_list)
print('Numpy array 1D:', my_numpy_array)
print('Kích thước:', my_numpy_array.shape)

# 3.2. Array 2-chiều (Ma trận) [cite: 28]
c = np.array([(1, 2, 3), (4, 5, 6)])
print('\nArray 2D:\n', c)
print('Shape:', c.shape)

# 3.4. Tạo mảng với giá trị 0 hoặc 1 [cite: 68]
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('\nZero matrix:\n', e)
print('One matrix:\n', f)

Numpy array 1D: [ 1  9 15 39]
Kích thước: (4,)

Array 2D:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 3.5.1. Reshape - Thay đổi kích thước [cite: 83]
g = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
h = g.reshape(3, 4) # Chuyển về 3 dòng 4 cột [cite: 104, 105]
print('Reshape (3, 4):\n', h)

# 3.5.2. Flatten - Chuyển về 1 chiều [cite: 146]
j = g.flatten()
print('\nFlatten array:', j)

# 3.6. Nối mảng hstack (ngang) và vstack (dọc) [cite: 170, 171, 172]
f_arr = np.array([1., 2., 3.])
g_arr = np.array([4., 5., 6.])
print('\nHorizontal Stack:', np.hstack((f_arr, g_arr)))
print('Vertical Stack:\n', np.vstack((f_arr, g_arr)))

Reshape (3, 4):
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

Flatten array: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]

Horizontal Stack: [1. 2. 3. 4. 5. 6.]
Vertical Stack:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# 3.7.1. Sinh mảng số nguyên ngẫu nhiên [cite: 187]
rand_int = np.random.randint(100, size=(3, 4))
print('Random 2D Int:\n', rand_int)

# 3.7.3. Phân phối chuẩn Gaussian [cite: 245, 247]
# loc: trung tâm, scale: độ lệch chuẩn, size: số phần tử
gauss = np.random.normal(5, 0.5, 10)
print('\nGaussian distribution:', gauss)

# 3.9. Sinh dãy số [cite: 300]
arr_range = np.arange(1, 20, 2) # [cite: 306]
arr_linspace = np.linspace(1., 5., num=10) # Chia đều khoảng [cite: 312, 313]
print('\nArange:', arr_range)
print('Linspace:', arr_linspace)

Random 2D Int:
 [[76 31 76 61]
 [25  8  9 60]
 [ 9 11 12 64]]

Gaussian distribution: [5.76562762 4.83730718 5.34040833 5.67802409 4.81961796 4.78688486
 5.24875337 5.62590751 4.73749147 5.37740755]

Arange: [ 1  3  5  7  9 11 13 15 17 19]
Linspace: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print('First row:', a[0]) # [cite: 327]
print('Second column:', a[:, 1]) # [cite: 331]
print('First two values of second row:', a[1, :2]) # [cite: 333]

First row: [1 2 3]
Second column: [2 5]
First two values of second row: [4 5]


In [ ]:
import pandas as pd

# 6. Tạo Series [cite: 352]
s = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print('Pandas Series:\n', s)

# 7. Tạo DataFrame từ Dictionary [cite: 384, 404]
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print('\nDataFrame:\n', df_dic)

# 7.1. Thao tác trên DataFrame [cite: 447]
# Nối (Concat), Xóa trùng (Drop duplicates), Sắp xếp (Sort) [cite: 457, 460, 462]
df1 = pd.DataFrame({'Name': ['John', 'Smith'], 'Age': [25, 30]})
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [26, 11]})
df_concat = pd.concat([df1, df2])
print('\nSau khi nối và xóa trùng Name:\n', df_concat.drop_duplicates('Name'))

Pandas Series:
 a    1.0
b    2.0
c    3.0
dtype: float64

DataFrame:
     Name  Age
0   John   30
1  Smith   40

Sau khi nối và xóa trùng Name:
     Name  Age
0   John   25
1  Smith   30
0   Adam   26


In [ ]:
import numpy as np
import pandas as pd

print("--- GIẢI BÀI TẬP ---")

# Bài 1 & 2: Mảng 3x3 [0,20], kiểm tra all/any [cite: 572, 573, 574]
arr_ex = np.random.randint(0, 21, size=(3, 3))
print("1. Mảng ngẫu nhiên:\n", arr_ex)
print("Kiểm tra tất cả khác 0:", np.all(arr_ex != 0))
print("Kiểm tra có ít nhất 1 phần tử khác 0:", np.any(arr_ex != 0))

# Bài 4: Mảng 10 số 1, 10 số 0, 10 số 5 [cite: 575]
arr4 = np.concatenate([np.ones(10), np.zeros(10), np.full(10, 5)])
print("\n4. Mảng 1, 0, 5:\n", arr4)

# Bài 5: Số chẵn từ 30 đến 70 [cite: 576]
arr5 = np.arange(30, 71, 2)
print("\n5. Số chẵn [30, 70]:\n", arr5)

# Bài 6: Ma trận đơn vị 3x3 [cite: 577]
arr6 = np.identity(3)
print("\n6. Ma trận đơn vị:\n", arr6)

# Bài 10: Ma trận 10x10 biên 1, trong 0 [cite: 585]
arr10 = np.ones((10, 10))
arr10[1:-1, 1:-1] = 0
print("\n10. Ma trận biên 1:\n", arr10)

# Bài 11: Đường chéo chính 1,2,3,4,5 [cite: 586]
arr11 = np.diag([1, 2, 3, 4, 5])
print("\n11. Ma trận diag:\n", arr11)

# Bài 15: Cộng trừ nhân chia Series [cite: 591]
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])
print("\n15. Cộng 2 Series:\n", s1 + s2)

# --- PHẦN BÀI TẬP TỪ DỮ LIỆU BÀI 22 --- [cite: 706, 707, 708, 709, 710, 711]
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)

print("\n23. 3 dòng đầu tiên:\n", df.head(3)) # [cite: 712]
print("\n24. Cột name và score:\n", df[['name', 'score']]) # [cite: 713]
print("\n25. Dòng có attempts > 2:\n", df[df['attempts'] > 2]) # [cite: 714]
print("\n27. Dòng có score là NaN:\n", df[df['score'].isnull()]) # [cite: 716]
print("\n28. Score trong khoảng [15, 20]:\n", df[df['score'].between(15, 20)]) # [cite: 717]

# Bài 30: Thay đổi giá trị dòng 'd', cột score thành 19 [cite: 719]
df.loc['d', 'score'] = 19
print("\n30. Sau khi sửa dòng 'd':\n", df.loc['d'])

--- GIẢI BÀI TẬP ---
1. Mảng ngẫu nhiên:
 [[ 9  6  2]
 [ 6 14  6]
 [11 15  8]]
Kiểm tra tất cả khác 0: True
Kiểm tra có ít nhất 1 phần tử khác 0: True

4. Mảng 1, 0, 5:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]

5. Số chẵn [30, 70]:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

6. Ma trận đơn vị:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

10. Ma trận biên 1:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

11. Ma trận diag:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

15. Cộng 2 Series:
 0     3
1     7
2    11
3    15
4    20
dtype: int64

23. 3 dòng đầu tiên:
         name  score  attempts qualify
a  Anastasia   12